---
- name: cronjob for restarting polkadot service
  cron:
    name: "restart polkadot"
    minute: "{{ polkadot_restart_minute }}"
    hour: "{{ polkadot_restart_hour }}"
    day: "{{ polkadot_restart_day }}"
    month: "{{ polkadot_restart_month }}"
    weekday: "{{ polkadot_restart_weekday }}"
    job: "/bin/systemctl restart polkadot.service"
  when: "polkadot_restart_enabled|default(false)|bool"

- name: register public ip
  uri:
    url: https://api.ipify.org?format=json
  register: public_ip

- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600
